
BEGIN;
DROP TABLE IF EXISTS Runder;
DROP TABLE IF EXISTS Skade;
DROP TABLE IF EXISTS Form;
DROP TABLE IF EXISTS Konkurranse;
DROP TABLE IF EXISTS Standardokt;
DROP TABLE IF EXISTS Bevegelsesform;
DROP TABLE IF EXISTS Standardokt_list;
DROP TABLE IF EXISTS Trening;
COMMIT;
